# Ros Topics
# image0_topic: "/left_r200/camera/color/image_raw"
# image1_topic: "/right_r200/camera/color/image_raw"

image0_topic: "/DualFactor/down/leftImage"
image1_topic: "/DualFactor/down/rightImage"

visualize: true

# Intrinsic Camera Paramters
fx: 385.7544860839844
fy: 385.7544860839844
cx: 323.1204833984375
cy: 236.7432098388672
k1: 0.0
k2: 0.0
p1: 0.0
p2: 0.0
k3: 0.0
width: 640
height: 480

# Extrinsic Camera Paramters 
baseline: .1
# initX: 0.0
# initY: 0.0
# initZ: 1.25
# initRoll: 0.0
# initPitch: 0.5
# initYaw: 0.0
initX: 3.75
initY: 0 #0
initZ: 1.25
initRoll: 0.0
initPitch: 0.0 #0.75 #0.62 #0.0
initYaw: 1.570796


 
 
