cam0:
  T_cam_imu:
    [0.0, -1.0, 0.0, 0.0,
     0.0, 0.0, -1.0, 0.0,
     1.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 1.0]

  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.0,0.0,0.0,0.0]
  distortion_model: radtan
  intrinsics: [554.3827128, 554.3827128, 320.5, 240.5]
  resolution: [640, 480]
  rostopic: /left_r200/camera/color/image_raw
  timeshift_cam_imu: 0.0
cam1:
  T_cn_cnm1:
    [1.0, 0.0, 0.0, -0.1,
     0.0, 1.0, 0.0, 0.0,
     0.0, 0.0, 1.0, 0.0,
     0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.0,0.0,0.0,0.0]
  distortion_model: radtan
  intrinsics: [554.3827128, 554.3827128, 320.5, 240.5]
  resolution: [640, 480]
  rostopic: /right_r200/camera/color/image_raw
  timeshift_cam_imu: 0.0


  